// Generated by CoffeeScript 1.10.0
(function() {
  var hello;

  hello = function(name) {
    if (name == null) {
      name = 'Anton';
    }
    return "Hello " + name;
  };

  console.log(hello());

}).call(this);
